services:
  - type: web
    name: hassan-pharmacy-api
    runtime: docker
    plan: free
    dockerContext: .
    dockerfilePath: ./Dockerfile
    healthCheckPath: /health
    autoDeploy: true
    envVars:
      - key: DATABASE_URL
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "1440"
      - key: FRONTEND_URL
        sync: false
